// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parkingLotAPI.Data;

#nullable disable

namespace parkingLotAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805075745_ParkingDB")]
    partial class ParkingDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("parkingLotAPI.Models.ParkingSpot", b =>
                {
                    b.Property<string>("SpotID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SpotID");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("parkingLotAPI.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpotID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationID");

                    b.HasIndex("SpotID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("parkingLotAPI.Models.Reservation", b =>
                {
                    b.HasOne("parkingLotAPI.Models.ParkingSpot", "ParkingSpot")
                        .WithMany("ReservationHistory")
                        .HasForeignKey("SpotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingSpot");
                });

            modelBuilder.Entity("parkingLotAPI.Models.ParkingSpot", b =>
                {
                    b.Navigation("ReservationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
